---

- hosts: all
  become: true
  pre_tasks:

  - name: install apache2 package and php packages
    tags: apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: copy default html file for site
    tags: apache
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
#- hosts: web_servers
#  become: true
#  tasks:
#
#  - name: this is an example
#    apt:
#      name:
#        - packagename0
#        - packagename1
#
#- hosts: db_servers
#  become: true
#  tasks:
#
#  - name: install mariadb package
#    apt:
#      name: mariadb-server
#      state: latest
#    when: ansible_distribution == "Debian"
#
#- hosts: file_servers
#  become: true
#  tasks:
#
#  - name: install samba package
#    package:
#      name: samba
#      state: latest
#
#
#
#
#
#
